buatberita/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^$', views.post_list, name='post_list'),
    #url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^$', views.post_new, name='post_new'),
    url(r'^new/', views.new_article, name='new_article'),
    url(r'^result/', views.create_news_form, name='news_form')
]

pollingberita/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.choosePolling, name='add-polling'),
    url(r'^pollingberita/', views.newspolling_form, name='polling-berita')
]

pollingumum/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.general_polling_form, name='gen-poll')
]

registration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.forms import UserCreationForm
from django.conf.urls import include, url
from BMNC import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('BMNC/', include('django.contrib.auth.urls'))
]

tkbasdat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import buatberita.urls as buatberita
import pollingberita.urls as pollingberita
import pollingumum.urls as pollingumum

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tambah-berita/', include(buatberita,namespace='tambah-berita')),
    url(r'^buat-polling/', include(pollingberita,namespace='buat-polling')),
    url(r'^polling-umum/', include(pollingumum,namespace='polling-umum')),
]

buatberita/models.py
from django.db import models

# Create your models here.

halamanutama/models.py
from django.db import models

# Create your models here.

pollingberita/models.py
from django.db import models

# Create your models here.

pollingumum/models.py
from django.db import models

# Create your models here.

buatberita/forms.py
from django import forms

class News_Form(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    number_attrs = {
        'class': 'form-control',
        'min': 0
    }
    judul = forms.CharField(label='Judul', required=True, max_length=50, widget=forms.TextInput(attrs))
    url = forms.URLField(label='Url', required=True, max_length=50, widget=forms.URLInput(attrs))
    topik = forms.CharField(label='Topik', required=True, max_length=50, widget=forms.TextInput(attrs))
    jumlahkata = forms.IntegerField(label='Jumlah Kata',required=True, widget=forms.NumberInput(number_attrs))
    tag = forms.CharField(label='Tag', required=True, max_length=50, widget=forms.TextInput(attrs))

buatberita/views.py
from django.shortcuts import render
from .forms import News_Form
import datetime
# Create your views here.
response = {}
def post_new(request):
	html = 'buatberita/add_news.html'
	response['news_form'] = News_Form
	return render(request, html, response)

def new_article(request):
	html = 'buatberita/post_edit.html'
	return render(request, html, response)

def create_news_form(request):
	if (request.method == "POST"):
		userlogin = request.session['username']
		judul = request.POST['judul']
		url = request.POST['url']
		topik = request.POST['topik']
		jmlkata = request.POST['jumlahkata']
		tag = request.POST['tag']
		response['judul'] = judul
		response['url'] = url
		response['topik'] = topik
		response['jumlahkata'] = jmlkata
		response['tag'] = tag
		cursor.execute('''INSERT INTO BERITA(url,judul,topik,jumlah_kata) VALUES(%s, %s, %s, %s) ''', [url, judul, topik,jmlkata])
		cursor.execute('''INSERT INTO TAG(url,tag) VALUES(%s, %s) ''', [url, tag])
		html = 'buatberita/result.html'
		return render(request, html, response)

halamanutama/views.py
from django.shortcuts import render

# Create your views here.

pollingberita/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
response = {}
def choosePolling(request):
	html = 'pollingberita/choose_polling.html'
	return render(request, html, response)

def newspolling_form(request):
	html = 'pollingberita/news_form.html'
	return render(request, html, response)

def create_general_polling(request):
	urlberita = request.POST['urlberita']
	mulai = request.POST['start']
	selesai = request.POST['finish']
	#cursor.execute('''INSERT INTO POLLING(id_polling,polling_start,polling_end,total_responden) VALUES(%s, %s, %s,0) ''', [mulai, selesai])
	#cursor.execute('''INSERT INTO POLLING_BERITA(id_polling,url_berita) VALUES(%s, %s) ''', [urlberita])

pollingumum/views.py
from django.shortcuts import render

# Create your views here.
response = {}
def general_polling_form(request):
	html = 'pollingumum/polling_biasa.html'
	#response['general_form'] = General_Form
	return render(request, html, response)

def create_news_poll(request):
	if(request.method == 'POST'):
		deskripsi = request.POST['desc']
		mulai = request.POST['start']
		selesai = request.POST['finish']
		url = "https://www.pollingumum.com/polling"
		#cursor.execute('''INSERT INTO POLLING(id_polling,polling_start,polling_end,total_responden) VALUES(%s, %s, %s,0) ''', [mulai, selesai])
		#cursor.execute('''INSERT INTO POLLING_BIASA(id_polling,url,deskripsi) VALUES(%s, %s, %s) ''', [id_polling, url, deskripsi])

	

buatberita/templates/buatberita/add_news.html
{% extends 'buatberita/layout/base.html' %}

{% block content %}
<div class="product-card">
  <div class="product-details">
    <h1>Berita</h1>
    <a type="button" class="btn" href="{% url 'tambah-berita:new_article' %}"><h5 style="margin-top: 10px">Tambah Berita</h5></a>
  </div>
</div>
{% endblock %}

buatberita/templates/buatberita/layout/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Tambah Berita</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'css/create_form.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/addnews.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/headstyle.css' %}" />
        <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    </head>
    <body>
        <header>
            {% include "buatberita/partials/header.html" %}
        </header>
            {% block content %}
            {% endblock %}
    </body>
</html>

buatberita/templates/buatberita/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
	<div id='cssmenu'>
		<ul>
		   <li class='active'><a href='#'>Home</a></li>
		   <li><a href="{% url 'tambah-berita:post_new' %}" >Tambah Berita</a></li>
		   <li><a href="{% url 'buat-polling:add-polling' %}" >Tambah Polling</a></li>
		</ul>
	</div>
</nav>

buatberita/templates/buatberita/post_edit.html
{% extends 'buatberita/layout/base.html' %}

{% block content %}
<div class="container">  
  <form id="contact" action="{% url 'tambah-berita:news_form' %}" method="post">
  	{% csrf_token %}
    <h3>Tambah Artikel</h3>
    <!-- <fieldset>
      <h4>Judul</h4>
      <input placeholder="Judul" type="text" tabindex="1" required autofocus>
    </fieldset>
    <fieldset>
      <h4>Url</h4>
      <input placeholder="Url" type="url" tabindex="2" required>
    </fieldset>
    <fieldset>
      <h4>Topik</h4>
      <input placeholder="Topik" type="text" tabindex="3" required>
    </fieldset>
    <fieldset>
      <h4>Jumlah Kata</h4>
      <input placeholder="Jumlah Kata" type="number" tabindex="4" required>
    </fieldset>
    <fieldset>
      <h4>Tag</h4>
      <input placeholder="Tag" type="text" tabindex="5" required>
    </fieldset> -->
    {{ news_form }}
    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}

buatberita/templates/buatberita/result.html
<p>{{ judul }}</p>
<br>
<p>{{ url }}</p>
<br>
<p>{{ topik }}</p>
<br>
<p>{{ jumlahkata }}</p>
<br>
<p>{{ tag }}</p>

pollingberita/templates/pollingberita/choose_polling.html
{% extends 'pollingberita/layout/base.html' %}

{% block content %}
<div class="product-card">
  <div class="product-details">
    <h1>Polling</h1>
    <a type="button" class="btn" href="{% url 'buat-polling:polling-berita' %}"><h5 style="margin-top: 10px">Tambah Polling Berita</h5></a>
    <a type="button" class="btn" href="{% url 'polling-umum:gen-poll' %}"><h5 style="margin-top: 10px">Tambah Polling Biasa</h5></a>
  </div>
</div>
{% endblock %}

pollingberita/templates/pollingberita/layout/base.html
{% load staticfiles %}
{% load static %}
<html>
    <head>
        <title>Polling Berita</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'css/chosepolling.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/newsform.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/styleheader.css' %}" />
        <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    </head>
    <body>
        <header>
            {% include "pollingberita/partials/header.html" %}
        </header>
        {% block content %}
        {% endblock %}
    </body>
</html>

pollingberita/templates/pollingberita/news_form.html
{% extends 'pollingberita/layout/base.html' %}
{% load staticfiles %}
{% load static %}

{% block content %}
<div class="container">  
  <form id="contact" action="" method="post">
  	{% csrf_token %}
    <h3>Polling Form</h3>
    <fieldset>
      <h4>Url</h4>
      <input class="form-control" type="url" tabindex="1" required autofocus>
    </fieldset>
    <fieldset>
      <h4>Waktu Mulai</h4>
      <input class="form-control" type="datetime-local" tabindex="2" required>
    </fieldset>
    <fieldset>
      <h4>Waktu Selesai</h4>
      <input class="form-control" type="datetime-local" tabindex="3" required>
    </fieldset>
    <fieldset>
      <h4>Pertanyaan Seputar Polling</h4>
      <input class="form-control" type="text" tabindex="4" required>
    </fieldset>
    <fieldset>
      <h4>Pertanyaan Seputar Polling</h4>
      <input class="form-control" type="text" tabindex="5" required>
    </fieldset>
    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}

pollingberita/templates/pollingberita/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
	<div id='cssmenu'>
		<ul>
		   <li class='active'><a href='#'>Home</a></li>
		   <li><a href="{% url 'tambah-berita:post_new' %}" >Tambah Berita</a></li>
		   <li><a href="{% url 'buat-polling:add-polling' %}" >Tambah Polling</a></li>
		</ul>
	</div>
</nav>

pollingumum/templates/pollingumum/layout/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Polling Biasa</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'css/genpollform.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/headerstyle.css' %}" />
        <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    </head>
    <body>
        <header>
            {% include "pollingumum/partials/header.html" %}
        </header>
        <div class="content container">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

pollingumum/templates/pollingumum/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
	<div id='cssmenu'>
		<ul>
		   <li class='active'><a href='#'>Home</a></li>
		   <li><a href="{% url 'tambah-berita:post_new' %}" >Tambah Berita</a></li>
		   <li><a href="{% url 'buat-polling:add-polling' %}" >Tambah Polling</a></li>
		</ul>
	</div>
</nav>

pollingumum/templates/pollingumum/polling_biasa.html
{% extends 'pollingumum/layout/base.html' %}

{% block content %}
<div class="container">  
  <form id="contact" action="" method="post">
  	{% csrf_token %}
    <h3>Polling Form</h3>
    <fieldset>
      <h4>Deskripsi</h4>
      <textarea class="form-control" type="text" tabindex="1" name="desc" required autofocus></textarea>
    </fieldset>
    <fieldset>
      <h4>Waktu Mulai</h4>
      <input class="form-control" type="datetime-local" tabindex="2" name="start" required>
    </fieldset>
    <fieldset>
      <h4>Waktu Selesai</h4>
      <input class="form-control" type="datetime-local" tabindex="3" name="finish" required>
    </fieldset>
    <fieldset>
      <h4>Pertanyaan Seputar Polling</h4>
      <input class="form-control" type="text" tabindex="4" name ="question1" required>
    </fieldset>
    <fieldset>
      <h4>Pertanyaan Seputar Polling</h4>
      <input class="form-control" type="text" tabindex="5" name ="question2" required>
    </fieldset>
    <!-- {{ general_form }} -->
    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}

pollingumum/templates/pollingumum/result.html
<p>{{ desc }}</p>
<br>
<p>{{ start }}</p>
<br>
<p>{{ finish }}</p>
<br>
<p>{{ question1 }}</p>
<br>
<p>{{ question2 }}</p>